In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]
b=np.array(l)

In [3]:
b

array([1, 2, 3, 4])

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
b=np.arange(16)

In [16]:
b.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
b.shape

(16,)

# Random

In [29]:
np.random.randint(2,10,10)

array([3, 7, 5, 2, 9, 6, 8, 8, 6, 5])

In [125]:
np.random.randn(3,3) #normal distributed values of size 3*3 

array([[ 0.96676727,  0.67324853,  1.41555421],
       [-0.91349279,  0.97690459, -0.1171933 ],
       [ 1.93312662, -0.27039962,  0.06000292]])

In [32]:
np.random.rand(3,6)*10

array([[5.43108819, 6.79725696, 0.96396413, 3.44923843, 7.66563471,
        9.19461968],
       [4.31157251, 7.91023976, 2.24679029, 6.46108641, 6.69072239,
        4.57605456],
       [6.28113748, 6.52426682, 1.66027357, 0.16852649, 2.89435046,
        6.24455658]])

In [33]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [37]:
a=np.array([2,4,6,7])

In [38]:
a

array([2, 4, 6, 7])

In [39]:
a.shape

(4,)

In [40]:
a.size

4

In [43]:
a=a.reshape((2,2))

In [44]:
a

array([[2, 4],
       [6, 7]])

In [45]:
a.shape

(2, 2)

In [46]:
a.size

4

In [47]:
a.ndim

2

In [48]:
a.astype(complex)

array([[2.+0.j, 4.+0.j],
       [6.+0.j, 7.+0.j]])

In [49]:
a

array([[2, 4],
       [6, 7]])

In [50]:
a.min()

2

In [51]:
a.max()

7

In [52]:
a.std()

1.920286436967152

In [53]:
a.mean()

4.75

In [58]:
a.sum()

19

In [59]:
a

array([[2, 4],
       [6, 7]])

In [60]:
a.sum(axis=1)

array([ 6, 13])

In [61]:
a.sum(axis=0)

array([ 8, 11])

In [64]:
np.sqrt(a)

array([[1.41421356, 2.        ],
       [2.44948974, 2.64575131]])

In [65]:
a

array([[2, 4],
       [6, 7]])

In [67]:
a.std()

1.920286436967152

In [68]:
np.std(a)

1.920286436967152

In [70]:
c=np.array(([2,3],[1,3]))
d=np.array(([7,2],[8,3]))

In [71]:
c

array([[2, 3],
       [1, 3]])

In [72]:
d

array([[7, 2],
       [8, 3]])

In [74]:
c+d

array([[9, 5],
       [9, 6]])

In [75]:
c*d

array([[14,  6],
       [ 8,  9]])

In [76]:
np.matmul(c,d)

array([[38, 13],
       [31, 11]])

In [77]:
c/d

array([[0.28571429, 1.5       ],
       [0.125     , 1.        ]])

In [79]:
c.dot(d)

array([[38, 13],
       [31, 11]])

# Complex Numbers

In [82]:
aa=np.array([2+3j,5+1j],dtype='complex')

In [83]:
aa

array([2.+3.j, 5.+1.j])

In [84]:
bb=np.array([1+3j,2+1j],dtype='complex')

In [85]:
aa+bb

array([3.+6.j, 7.+2.j])

In [86]:
aa*bb

array([-7.+9.j,  9.+7.j])

In [87]:
aa.dot(bb)

(2+16j)

# Exercise

In [97]:
ap=np.arange(1,10).reshape(3,-1)

In [99]:
ap

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
ap=ap.ravel()

In [103]:
ap

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
ap[ap>=5]

array([5, 6, 7, 8, 9])

In [106]:
ap[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
ap=ap.reshape(3,-1)

In [117]:
ap.shape

(3, 3)

In [119]:
ap[1][2]

6

In [134]:
hd=np.random.rand(3,4)

In [135]:
hd

array([[0.57809635, 0.28588604, 0.4477706 , 0.80394599],
       [0.61695694, 0.63675383, 0.21760563, 0.06556088],
       [0.51737481, 0.37700702, 0.18996296, 0.17582997]])

In [136]:
hd=hd*10

In [137]:
hd

array([[5.78096349, 2.85886041, 4.47770604, 8.03945989],
       [6.16956943, 6.36753829, 2.17605629, 0.65560875],
       [5.17374812, 3.77007024, 1.89962961, 1.75829973]])

In [140]:
hd=np.around(hd)

In [141]:
hd.astype(int)

array([[6, 3, 4, 8],
       [6, 6, 2, 1],
       [5, 4, 2, 2]])

In [156]:
dw=np.random.randint(1,10,5)

In [157]:
ha=dw

In [158]:
dw

array([4, 6, 1, 1, 5])

In [159]:
ha

array([4, 6, 1, 1, 5])

In [160]:
dw.sort()

In [161]:
dw

array([1, 1, 4, 5, 6])

In [162]:
ha

array([1, 1, 4, 5, 6])

In [163]:
# both are sorted it changes both arrays 

In [165]:
la=np.random.randint(1,6,3)

In [166]:
la

array([3, 1, 3])

In [167]:
ku=la

In [171]:
la=sorted(la)

In [172]:
la

[1, 3, 3]

In [173]:
ku

array([3, 1, 3])

In [178]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])